-- WITHHELD - not final.
-- This file was uploaded prematurely as part of the Servex marketing package and has been
-- withheld pending reconciliation with the codebase and the Jordan-first pivot.
-- See docs/JORDAN_PIVOT_PLAN.md (section 10) and docs/DECISIONS_JORDAN_PIVOT.md.
